### PR TITLE
updated the readme to be accurate wrt version

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Comment by EricWittmann** [comment]
How do we get the docker-hub image updated to 1.1.5.Final?  I thought it would just work but when I go here it still reads 1.1.4.Final:

https://registry.hub.docker.com/u/jboss/apiman-wildfly/dockerfile/

However, there does appear to be a 1.1.5.Final tag.  Sorry I don't know how this all hangs together. :(  The github repo seems right:

https://github.com/jboss-dockerfiles/apiman/blob/1.1.5.Final/apiman-wildfly/Dockerfile

**Comment by goldmann** [comment]
Basically:
1. PR is merged,
2. New tag is added on GitHub
3. New tag is added on Docker Hub
4. A new build is kicked on HUB.

**Comment by goldmann** [comment]
HUB sucks and we do not have control over the `Dockerfile` that is displayed in the provided link. If we rebuild - there is a high chance that it'll be what's in `latest` image, which is `1.1.5.Final`.

There is already a `1.1.5.Final` image available and it is also available as `latest`. Just the website is wrong.

**Comment by goldmann** [comment]
My proposal is to entirely remove the "latest version" section from the readme, because there is a very high chance that someone will forget to update this.

**Comment by EricWittmann** [comment]
OK I think I can handle the fact that just the website listing of the Dockerfile is wrong. :)  Thanks for the explanation.

+1 to removing the 'latest version' section from the readme!  It obviously hadn't been updated in ages.

**Pull request closed without merging**
